export const ActionTypes = {
  PRODUCTS_REQUEST: 'PRODUCTS_REQUEST',
  TOGGLE_LOADER: 'TOGGLE_LOADER',
  SET_PRODUCTS: 'SET_PRODUCTS',
  UPDATE_CART: 'UPDATE_CART',
  PRODUCT_DETAIL_REQUEST: 'PRODUCT_DETAIL_REQUEST',
  SET_PRODUCTS_DETAIL: 'SET_PRODUCTS_DETAIL',
};
